# ------------------------------------------------------------------------------
#                             Application settings
# ------------------------------------------------------------------------------
server.port=8080
spring.application.name=tableit
spring.profiles.active=${ENVIRONMENT:dev}


# ------------------------------------------------------------------------------
#                            Database configuration
# ------------------------------------------------------------------------------
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tableit_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true


# ------------------------------------------------------------------------------
#                                   Logging
# ------------------------------------------------------------------------------
logging.level.root=INFO
logging.level.com.paltsy=DEBUG
logging.file.name=logs/app.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n


# ------------------------------------------------------------------------------
#                              External services
# ------------------------------------------------------------------------------
auth.service.url=https://paltsyauth-dev.up.railway.app/
notification.service.url=${BOT_API_URL:https://paltsybot-dev.up.railway.app}
transaction.service.url=https://test.paltsy.eu/
telegram.service.url=${BOT_URL:https://t.me/vladCS_bot}

notification.service.api-key=${NOTIFICATION_SERVICE_API_KEY:qwrt}
# ------------------------------------------------------------------------------
#                              JWT KEYS
# ------------------------------------------------------------------------------

# Access Token RSA Keys (Base64 encoded)
jwt.private-key.access=${PRIVATE_ACCESS_KEY}
jwt.public-key.access=${PUBLIC_ACCESS_KEY}

# Refresh Token RSA Keys (Base64 encoded)
jwt.private-key.refresh=${PRIVATE_REFRESH_KEY}
jwt.public-key.refresh=${PUBLIC_REFRESH_KEY}


# ================= JWT EXPIRATION =================

# access token: 15 minutes
jwt.expiration.access-ms=900000

# refresh token: 7 days
jwt.expiration.refresh-ms=604800000

# action token ttl: 5 minutes
action-token.expiration-ms=300000

## ================= S3 Configuration =================
#S3_ENDPOINT=${S3_ENDPOINT}
#S3_BUCKET=${S3_BUCKET:paltsy-avatars}
#S3_REGION=${S3_REGION:us-east-1}
#S3_ACCESS_KEY=${S3_ACCESS_KEY}
#S3_SECRET_KEY=${S3_SECRET_KEY}

